import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  content: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 96, gap: 9 },
  header: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 1 },
  headerGlyph: { fontSize: 30, lineHeight: 34, fontWeight: "500" },
  title: { fontSize: 22, fontWeight: "800", lineHeight: 27 },
  previewNotice: { borderRadius: 10, paddingVertical: 8, paddingHorizontal: 11, borderWidth: 1 },
  previewText: { fontSize: 12, fontWeight: "600" },
  shizukuCard: { borderRadius: 14, padding: 10, borderWidth: 1, gap: 8 },
  syncButton: { minHeight: 34, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderWidth: 1, borderRadius: 9, paddingHorizontal: 9 },
  syncButtonText: { fontSize: 13, fontWeight: "800" },
  syncChevron: { fontSize: 21, lineHeight: 21, fontWeight: "700" },
  automaticTimeRow: { borderTopWidth: 1, paddingTop: 8, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  automaticTimeText: { flex: 1, paddingRight: 8 },
  automaticTimeTitle: { fontSize: 13, fontWeight: "800" },
  automaticTimeHint: { fontSize: 11, marginTop: 2 },
  card: { borderRadius: 14, padding: 12, borderWidth: 1 },
  cardHeading: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  cardTitle: { fontSize: 15, lineHeight: 20, fontWeight: "800" },
  nowButton: { borderWidth: 1, borderRadius: 8, paddingHorizontal: 9, paddingVertical: 4 },
  nowButtonText: { fontSize: 12, fontWeight: "800" },
  row: { flexDirection: "row", gap: 8, marginTop: 9 },
  rowPrimary: { flex: 1.35 },
  rowSecondary: { flex: 1 },
  tripleRow: { flexDirection: "row", gap: 7, marginTop: 9 },
  fieldWrap: { flex: 1 },
  fieldLabel: { fontSize: 11, fontWeight: "700", marginBottom: 4 },
  input: { borderWidth: 1, borderRadius: 9, paddingHorizontal: 9, height: 40, fontSize: 15, fontWeight: "700" },
  repeatGroup: { marginTop: 8 },
  repeatGroupTitle: { fontSize: 11, fontWeight: "800" },
  repeatDivider: { height: 1, marginTop: 11 },
  logCard: { borderRadius: 14, borderWidth: 1, overflow: "hidden" },
  logToggle: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: 12 },
  chevron: { fontSize: 20, lineHeight: 20, fontWeight: "800" },
  logActions: { flexDirection: "row", gap: 6, paddingHorizontal: 12, paddingBottom: 8 },
  textAction: { paddingVertical: 5, paddingHorizontal: 7 },
  textActionLabel: { fontSize: 12, fontWeight: "800" },
  emptyLogText: { fontSize: 13, paddingHorizontal: 12, paddingBottom: 12 },
  logItem: { marginHorizontal: 10, marginBottom: 7, borderRadius: 10, padding: 9 },
  logTime: { fontSize: 10, fontWeight: "800", marginBottom: 3 },
  logMessage: { fontSize: 12, lineHeight: 16 },
  configurationHeader: { minHeight: 58, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 10, paddingVertical: 8 },
  saveConfigurationButton: { flexShrink: 1, borderWidth: 1, borderRadius: 9, paddingHorizontal: 11, paddingVertical: 8 },
  saveConfigurationButtonText: { fontSize: 13, fontWeight: "800" },
  configurationToggle: { width: 44, height: 40, marginLeft: 28, alignItems: "center", justifyContent: "center", borderRadius: 9 },
  configurationList: { paddingHorizontal: 10, paddingBottom: 10, gap: 7 },
  configurationEmptyText: { paddingHorizontal: 2, paddingBottom: 2 },
  configurationItem: { minHeight: 42, borderRadius: 10, paddingHorizontal: 11, paddingVertical: 9, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  configurationItemName: { flex: 1, fontSize: 13, fontWeight: "700" },
  configurationCurrent: { fontSize: 11, fontWeight: "800" },
  modalBackdrop: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 22, backgroundColor: "rgba(0,0,0,0.45)" },
  modalCard: { width: "100%", maxWidth: 430, borderWidth: 1, borderRadius: 16, padding: 16 },
  modalTitle: { fontSize: 18, fontWeight: "800" },
  modalHint: { fontSize: 12, marginTop: 5, marginBottom: 10 },
  modalInput: { height: 44, borderWidth: 1, borderRadius: 10, paddingHorizontal: 11, fontSize: 15, fontWeight: "700" },
  modalActions: { flexDirection: "row", justifyContent: "flex-end", gap: 8, marginTop: 14 },
  modalActionButton: { minHeight: 40, minWidth: 88, borderRadius: 10, alignItems: "center", justifyContent: "center", paddingHorizontal: 12 },
  modalSaveButton: { minWidth: 110 },
  modalCancelText: { fontSize: 13, fontWeight: "800" },
  modalSaveText: { color: "#FFFFFF", fontSize: 13, fontWeight: "800" },
  footer: { paddingHorizontal: 16, paddingVertical: 10, borderTopWidth: 1 },
  primaryButton: { height: 50, borderRadius: 14, alignItems: "center", justifyContent: "center" },
  stopButton: { minHeight: 50, borderRadius: 14, alignItems: "center", justifyContent: "center", paddingHorizontal: 10, paddingVertical: 8 },
  primaryButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800", textAlign: "center" },
  pressed: { opacity: 0.68, transform: [{ scale: 0.98 }] },
});
